# Generated by Django 4.0.4 on 2022-07-01 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['createdTime']},
        ),
        migrations.RenameField(
            model_name='note',
            old_name='created',
            new_name='createdTime',
        ),
    ]
